name: Release

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]

    permissions:
      contents: write # Required to create a tag and a GitHub release
      issues: write # Required to comment on resolved issues/PRs
      pull-requests: write # Required to comment on resolved issues/PRs

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - name: ‚¨áÔ∏è Checkout repository
        uses: actions/checkout@v5
        with:
          # Required for semantic-release to analyze the ENTIRE commit history
          fetch-depth: 0
          token: ${{ secrets.ISABELLE_RELEASE_TOKEN }}

      - name: ‚öôÔ∏è Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          # Enable cache for npm dependencies, speeding up future builds
          cache: "npm"

      - name: üì¶ Install dependencies
        run: npm ci

      - name: üöÄ Execute Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.ISABELLE_RELEASE_TOKEN }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: npx semantic-release
